name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install jq librsvg2-bin
      - name: Build
        run: /bin/bash -ue development/build.sh
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: dist/chrome_extension.zip

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: extension
      - name: Upload to Chrome Web Store
        env:
          CHROME_WEB_STORE_ID: ${{ secrets.CHROME_WEB_STORE_ID }}
          GOOGLE_API_CLIENT_ID: ${{ secrets.GOOGLE_API_CLIENT_ID }}
          GOOGLE_API_CLIENT_SECRET: ${{ secrets.GOOGLE_API_CLIENT_SECRET }}
          GOOGLE_API_REFRESH_TOKEN: ${{ secrets.GOOGLE_API_REFRESH_TOKEN }}
        run: /bin/bash -ue development/upload.sh chrome_extension.zip
